const UPDATE_WORD = 'UPDATE_WORD';
const FETCH_WORD_BEGIN = 'FETCH_WORD_BEGIN';
const FETCH_WORD_SUCCESS = 'FETCH_WORD_SUCCESS';
const FETCH_WORD_FAILURE = 'FETCH_WORD_FAILURE';
const UPDATE_SCORE = 'UPDATE_SCORE';

module.exports = {
  UPDATE_WORD,
  FETCH_WORD_BEGIN,
  FETCH_WORD_SUCCESS,
  FETCH_WORD_FAILURE,
  UPDATE_SCORE,
};
